resources:
    App\Entity\Category:
        operations:
            ApiPlatform\Metadata\GetCollection:
                normalizationContext:
                    groups: ["read:item"]
            ApiPlatform\Metadata\Get:
                openapi:
                    summary: 'hidden'
                normalizationContext:
                    groups: ["read:item"]
            ApiPlatform\Metadata\Post:
                normalizationContext:
                    groups: ["read:item"]
                denormalizationContext:
                    groups: ["write:item"]
            ApiPlatform\Metadata\Patch:
                normalizationContext:
                    groups: ["read:item"]
                denormalizationContext:
                    groups: ["write:item"]
            ApiPlatform\Metadata\Delete: ~
    App\Entity\Post:
        paginationItemsPerPage: 10
        paginationMaximumItemsPerPage: 100
        denormalizationContext:
            groups: ["write:item"]
        operations:
            count:
#                security: 'is_granted("CAN_VIEW", "post")'
                class: ApiPlatform\Metadata\GetCollection
                method: GET
                uriTemplate: /posts/count
                controller: App\Controller\PostCountController
#                filters: ['post.boolean_filter']
                parameters:
                    isOnline:
                        description: Filter article if online or no, all by default
                        castToNativeType: true
                        schema:
                            type: boolean
#                        filter: 'api_platform.doctrine.orm.boolean_filter'
                paginationEnabled: false
                openapi:
                    summary: Count articles
                    description: Count articles with filter online or no
                    responses:
                        200:
                            description: Ok
                            content:
                                "application/ld+json":
                                    schema:
                                        type: integer
                                        example: 3
                                "application/json":
                                    schema:
                                        type: integer
                                        example: 3
                read: false
            ApiPlatform\Metadata\GetCollection:
#                provider: App\State\PostCollectionProvider
#                parameters:
#                    id:
#                        filter: 'api_platform.doctrine.orm.search_filter'
#                        filterContext:
#                            strategy: 'exact'
#                    title:
#                        filter: 'api_platform.doctrine.orm.search_filter'
#                        filterContext:
#                            strategy: 'partial'
                filters: ['post.search_filter']
                normalizationContext:
                    groups: ["read:collection"]
                    openapi_definition_name: 'Collection'
            ApiPlatform\Metadata\Get:
                security: 'is_granted("CAN_VIEW", object)'
                normalizationContext:
                    groups: ["read:collection", "read:item"]
                    openapi_definition_name: 'Detail'
            ApiPlatform\Metadata\Post:
                inputFormats:
                    multipart: ['multipart/form-data']
                security: 'is_granted("ROLE_USER")'
                processor: App\State\UserOwnerStateProcessor
                normalizationContext:
                    groups: ["read:collection", "read:item"]
                validationContext:
                    groups: ['Default', 'create:item']
            ApiPlatform\Metadata\Patch:
                validationContext:
                    groups: ['App\Entity\Post', 'validationGroups']
            ApiPlatform\Metadata\Delete:
                security: 'is_granted("CAN_DELETE", object)'
            publish:
                class: ApiPlatform\Metadata\Post
                security: 'is_granted("CAN_EDIT", object)'
                method: POST
                uriTemplate: /posts/{id}/publish
                controller: App\Controller\PostPublishController
                deserialize: false
                openapi:
                    summary: Publish article
                    description: Change online article status
                    requestBody:
                        content:
                            - 'application/json':
                                  schema: []
#                read: false
#                write: false

    App\Entity\Media:
        paginationItemsPerPage: 10
        paginationMaximumItemsPerPage: 100
        operations:
            ApiPlatform\Metadata\GetCollection:
            ApiPlatform\Metadata\Get:
            ApiPlatform\Metadata\Post:
                processor: App\State\UserOwnerStateProcessor
            ApiPlatform\Metadata\Patch:
            ApiPlatform\Metadata\Delete: ~


